version: '3'
services:
  postgres:
    container_name: dimotociclodb
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dimotociclo-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - net
  api:
    container_name: api
    image: dimotociclo-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    restart: always
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: