spring:
  datasource:
    url: jdbc:postgresql://postgres-container:5432/dimotociclo-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: java.text.SimpleDateFormat
    serialization:
      write-dates-as-timestamps: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZZ} %magenta([%thread]) %highlight(%-5level) %logger.%M - %green(%msg%n)"
  level:
    br.com.projeto.dimotociclo: DEBUG
server:
  port: 8083
  servlet:
    context-path: /api
