spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZZ} %magenta([%thread]) %highlight(%-5level) %logger.%M - %green(%msg%n)"
  level:
    br.com.projeto.dimotociclo: DEBUG

server:
  port: 8082
  servlet:
    context-path: "/api"
